### ISSUE TITLE
What would make this 1.0?

### ISSUE THREAD

**Issue by steveklabnik** [QuietMisdreavus/init-with-rs#1]
Just out of curiosity, what do you think it'd take to have a 1.0 of this package? It seems small enough that it should be easy to do, but maybe not!

**Comment by QuietMisdreavus** [comment]
Not a whole lot, really. I think the answer boils down to "at least one person other than me looking at it and saying 'looks good to me'". I'd say it's 1.0-ready right now, but I haven't actually *used* it, merely dreamed up the API and put it together. There's not a whole lot here, so it wouldn't take a lot to bother pushing the major version up.

**Comment by steveklabnik** [comment]
Neat. I've referred to it a lot over the last few days, so I was mostly just wondering.
